# Generated by Django 2.2.10 on 2020-03-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200322_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
